accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView
from .views.profile import CreateProfile

app_name = 'accounts'
urlpatterns = [
	path("create-profile/", CreateProfile.as_view(), name="create_profile"),

]

music_man/urls.py
from django.urls import re_path as url, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static

from django.conf import settings

from suggestions.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", home, name='home_url'),
    path("suggestion/", include('suggestions.urls'))
]

suggestions/urls.py
from django.urls import re_path as url, path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # path("", views.home, name='home_url'),
    path("", views.suggestion, name='suggestion_url')

]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Profile(models.Model):
    user = models.ForeignKey(User, related_name="profile", on_delete=models.CASCADE)
    display_name = models.CharField(max_length=50)
    bio = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/%Y/%m/%d', null=True, blank=True)

    def __str__(self):
        return self.display_name

base/models.py
from django.db import models


# Create your models here.
class BaseAbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    created_by = models.CharField(max_length=255, null=True, blank=True)
    updated_by = models.CharField(max_length=255, null=True, blank=True)

    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True

movie_bank/models/movie.py
from django.db import models

# Create your models here.
from base.models import BaseAbstractModel


class Genre(BaseAbstractModel):
    name = models.CharField(max_length=255, unique=True)


class Movie(BaseAbstractModel):
    title = models.CharField(max_length=255)
    release_date = models.DateField(null=True, blank=True)
    imdb_id = models.CharField(max_length=255, null=True, blank=True)
    imdb_rating = models.FloatField(null=True, blank=True)
    imdb_votes = models.IntegerField(null=True, blank=True)
    imdb_url = models.URLField(null=True, blank=True)
    poster_url = models.URLField(null=True, blank=True)
    trailer_url = models.URLField(null=True, blank=True)
    plot = models.TextField(null=True, blank=True)
    director = models.CharField(max_length=255, null=True, blank=True)
    writer = models.CharField(max_length=255, null=True, blank=True)
    actors = models.CharField(max_length=255, null=True, blank=True)
    genre = models.ManyToManyField(Genre, blank=True)
    runtime = models.IntegerField(null=True, blank=True)
    language = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.title)

suggestions/models.py
from django.db import models


# Create your models here.
class Movies(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    genre = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    img_link = models.URLField(max_length=500, blank=True, null=True)
    rating = models.CharField(max_length=5, blank=True, null=True)
    votes = models.CharField(max_length=5, blank=True, null=True)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import User
from django.views import View
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

accounts/views/profile.py
from django.shortcuts import render
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import User
from django.views import View
from accounts.models import Profile
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

class CreateProfile(View):
    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        user = request.user
        profile = Profile.objects.get(user = user)
        print(profile.profile_picture.url)
        context = {
            'user': user,
            'profile': profile
        }
        return render(request, "accounts/profile_create.html", context)

    def post(self, request):
        pass

base/views.py
from django.shortcuts import render

# Create your views here.

movie_bank/views/views.py
from django.shortcuts import render

# Create your views here.

suggestions/views.py
import datetime
import random

from bs4 import BeautifulSoup
from django.shortcuts import render
from requests import get

# Create your views here.
from suggestions.services.perser_service import ImdbWebParser


def home(request):
    return render(request, 'suggestions/movie_home.html')


def suggestion(request):
    if request.method == 'GET':
        release_date_from = request.GET['release_date_from'] if request.GET['release_date_from'] \
            else (datetime.datetime.now() - datetime.timedelta(days=3*365)).strftime('%Y-%m-%d')

        release_date_to = request.GET['release_date_to'] if request.GET['release_date_to'] \
            else datetime.datetime.now().strftime('%Y-%m-%d')

        user_rating_from = request.GET['user_rating_from'] if request.GET['user_rating_from'] else "5"
        user_rating_to = request.GET['user_rating_to'] if request.GET['user_rating_to'] else "10"
        tv_movie = 'tv_movie'

        genre = request.GET['genre']

        success = False
        retry_count = 0
        while not success and retry_count < 10:
            try:
                movie_container = ImdbWebParser().get_movie(tv_movie, release_date_from, release_date_to,
                                                            user_rating_from,
                                                            user_rating_to, genre)
                suggested_movie = random.choice(movie_container)
                success = True
            except IndexError:
                retry_count += 1
                print(retry_count)

        movie_name = suggested_movie.h3.a.text
        movie_rating = float(suggested_movie.strong.text)
        movie_votes = suggested_movie.find('span', attrs={'name': 'nv'})['data-value']
        about_movie = suggested_movie.find('span', attrs={'class': 'genre'}).text

        main_page = suggested_movie.h3.a['href']
        main_page = "http://www.imdb.com/" + main_page
        main_response = get(main_page)
        main_html = BeautifulSoup(main_response.text, 'html.parser')

        image = main_html.find('img', class_='ipc-image')["src"]
        summary = main_html.find('span', class_='kgphFu').text

        context = [
            movie_name,
            movie_rating,
            movie_votes,
            about_movie,
            image,
            summary
        ]

        # print(len(movie_container))
        # # print(image)
        # # print(img_trailer)
        # # print(release_date_from)
        # # print(release_date_to)
        # # print(genre)
        # # print(main_page)

        # print(user_rating_from)
        # print(user_rating_to)
        # print(genre)
        # print(release_date_from)
        # print(release_date_to)
        # print(video)

        return render(request, 'suggestions/movie_home.html', {'context': context})

# url = 'https://www.imdb.com/search/title?title_type=tv_movie&release_date='\
# +release_date_from+','\
# +release_date_to+\
# '&user_rating='+user_rating_from+','\
# +user_rating_to+\
# '&genres='+genre+\
# '&sort=num_votes,desc&page='+str(1)

accounts/templates/accounts/profile_create.html
{% extends 'nav_footer.html' %}
{% block main_content %}
<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            <img src="{{ profile.profile_picture.url }}" alt=""/>
                            <div class="file btn btn-lg btn-primary">
                                Change Photo
                                <input type="file" name="file"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{ profile.display_name }}
                                    </h5>
{#                                    <h6>#}
{#                                        Web Developer and Designer#}
{#                                    </h6>#}
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>WORK LINK</p>
                            <a href="">Website Link</a><br/>
                            <a href="">Bootsnipp Profile</a><br/>
                            <a href="">Bootply Profile</a>
                            <p>SKILLS</p>
                            <a href="">Web Designer</a><br/>
                            <a href="">Web Developer</a><br/>
                            <a href="">WordPress</a><br/>
                            <a href="">WooCommerce</a><br/>
                            <a href="">PHP, .Net</a><br/>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>User Id</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ user.username }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ profile.display_name }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{ user.email }}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>123 456 7890</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Profession</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Web Developer and Designer</p>
                                            </div>
                                        </div>
                            </div>

                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Experience</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Hourly Rate</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>10$/hr</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Total Projects</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>230</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>English Level</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>Expert</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Availability</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>6 months</p>
                                            </div>
                                        </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <label>Your Bio</label><br/>
                                        <p>Your detail description</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>



    <style>
    body{
    {#background: -webkit-linear-gradient(left, #3931af, #00c6ff);#}

}
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background:#5b0763 ;

}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    {#background: #212529b8;#}
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #0d0d0d;
    font-style: italic;

}
.profile-head h6{
    {#color: #0062cc;#}
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    {#border-bottom:2px solid #0062cc;#}
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    {#color: #0062cc;#}
}
    </style>
{% endblock %}

suggestions/templates/suggestions/movie_home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Movies</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- javascript cdn -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" type="text/css" href="movie_home.css"> -->
    <link rel="stylesheet" href='{% static "suggestions/movie_home.css" %}' type="text/css">
    <link rel="icon" href='{% static "suggestions/img/tab-icon.png" %}'>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
</head>
<body>
<!-- navbar -->
<div id="loading"><img src="{% static "suggestions/img/loarder-1.gif" %}"/></div>

<div class="navbar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{{ home_url }}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Comming Soon</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Comming Soon</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li>
    </ul>
</div>
<!-- end navbar -->

<!-- start of greeting -->
<div class="greeting">
    <div class="container">
        <h1>Smart Movie Suggestor</h1>
        <h2>Search smartly</h2>
        <h3>Search Below</h3>

    </div>
</div>
<!-- end of greetings -->

<!-- search bars -->

<div class="search_bar">
    <div class="parallax">
        <div class="row">
            <div class="col"></div>
            <div class="col-auto">
                <h2>Search here</h2>
                <br>
                <br>
            </div>
            <div class="col"></div>
        </div>

        <div class="container">
            <form method="GET" action="/suggestion">
                <div class="row">

                    <div class="col col-sm-6">
                        <input class="form-control" type="date" placeholder="Release Date From" name="release_date_from"
                               value="{{ request.GET.release_date_from }}">
                    </div>
                    <div class="col col-sm-6">
                        <input class="form-control" type="date" placeholder="Release Date To" name="release_date_to"
                               value="{{ request.GET.release_date_to }}">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col col-sm-6">
                        <input class="form-control" type="text" placeholder="Rating From" name="user_rating_from"
                               value="{{ request.GET.user_rating_from }}">
                    </div>
                    <br>
                    <div class="col col-sm-6">
                        <input class="form-control" type="text" placeholder="Rating To" name="user_rating_to"
                               value="{{ request.GET.user_rating_to }}">
                    </div>
                </div>

                <br>
                <div class="row">
                    <div class="col ">
                        <select class="custom-select" name="genre">
                            <option value={{ request.GET.genre }}>Choose...</option>
                            <option value="action">Action</option>
                            <option value="horror">Horror</option>
                            <option value="drama">Drama</option>
                            <option value="fantasy">Fantasy</option>
                            <option value="history">History</option>
                            <option value="mystery">Mystery</option>
                            <option value="romance"> Romance</option>
                        </select>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col col-sm-6"></div>
                    <button id="submitBtn" type="submit" class="btn btn-block btn-success">Suggest Movie</button>
                    <br>
                    <br>
                    <div class="col"></div>
                </div>
                <div>
                    <br>
                </div>


            </form>

        </div>
    </div>

</div>


<!-- end of search bars -->
<br>
<!-- start of suggestion section -->
    <div class="suggestions">
        <div class="container">
            {% if context %}
                <div class="row">
                    <div class="col">
                        <h3>{{ context.0 }}</h3>
                        <P>{{ context.3 }}</P>
                        <p>Votes: {{ context.2 }}</p>
                        <p>Rating: {{ context.1 }}</p>
                        <p>About: {{ context.5 }}</p>

                        <!-- <button href="{{context.5}}" class="btn btn-primary">Submit</button> -->

                    </div>
                    <div class="col">
                        <img src="{{ context.4 }}" class="rounded float-right" alt="..." height="300" width="200">
                    </div>
                </div>
            {% endif %}
            <br>
            <div class="row">
                <div class="col">

                </div>
            </div>

        </div>
    </div>
<!-- end of suggestion section -->

<br>

<hr>
<!-- start about us -->
    <div class="about_us">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3>Contact us</h3>
                    <p>For any query email me on digantaprotik@gmail.com</p>
                </div>
                <div class="col">
                    <h3>About Site </h3>
                    <p>Search for suggestions here . Special Thanks to IMDB . The results are from IMDB . Enjoy Movie
                        suggested by us </p>
                </div>
                <div class="col">
                    <h3>Future features</h3>
                    <p>User account, watched list, share movie list etc .</p>
                </div>
            </div>
        </div>
    </div>
<!-- start about us -->
</body>
</html>
<script>
    $('#submitBtn').on('click', function (e) {
        $('#loading').show();
        $('#form').submit();
    });
</script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Movies</title>
	<!-- bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<!-- javascript cdn -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<!-- <link rel="stylesheet" type="text/css" href="movie_home.css"> -->
	<link rel="stylesheet" href='{% static "suggestions/movie_home.css" %}' type="text/css">
    <link rel="icon" href="{% static "suggestions/title_icon.ico" %}" />
</head>
<body>
	<!-- navbar -->

{% block content %}
{% endblock content %}

</body>
</html>

templates/nav_footer.html
{% extends 'base.html' %}
{% block content %}
	<div class="navbar">
		<ul class="nav">
		  <li class="nav-item">
		    <a class="nav-link active" href="{% url "home_url" %}">Home</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" href="{% url "accounts:create_profile" %}">Profile</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" href="#">Comming Soon</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link disabled" href="#">Disabled</a>
		  </li>
		</ul>
	</div>
    {% block main_content %}
    {% endblock %}

<hr>
	<!-- start about us -->
	<div class="about_us">
		<div class="container">
			<div class="row">
				<div class="col">
					<h3>Contact us</h3>
					<p>For any query email me on digantaprotik@gmail.com</p>
				</div>
				<div class="col">
					<h3>About Site </h3>
					<p>Search for suggestions here . Special Thanks to IMDB . The reaults are from IMDB . Enjoy Movie suggested by us </p>
				</div>
				<div class="col">
					<h3>Future features</h3>
					<p>Personal Watched  Movie list generation is coming .</p>
				</div>
			</div>
		</div>
	</div>
	<!-- start about us -->
{% endblock  %}